In [15]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import networkx as nx
import numpy as np

import mygraphs as mg
import utility as ut
from mygraphs.base_graph import BaseGraph
from mygraphs.standard_graphs import *
from mygraphs.directed_graphs import *
from mygraphs.weighted_graphs import *
from utility.graph_generator import *
from utility.data_transformer import DataTransformer

#import testing
#from testing.test_graphs import test_some_graphs

import os

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Graphs

### Standard Graphs

In [2]:
nodes = [0, 1, 2, 3, 4, 5, 6, 7]
edges = [(0, 1), (0, 0), (1, 1), (1, 1), (0, 3), (0, 3), (0, 5), (1, 2), (2, 4), (2 , 7), (3, 6), (3, 5), (5, 6), (6, 7)]
G = Graph(nodes, edges)

G.adjacency_matrix

array([[1., 1., 0., 2., 0., 1., 0., 0.],
       [1., 2., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [2., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0.]])

In [3]:
G.incidence_matrix

array([[1., 1., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 2., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.]])

In [4]:
G.degree_matrix

array([[5., 0., 0., 0., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2.]])

In [5]:
nodes = [0, 1, 2, 3, 4, 5, 6, 7]
edges = [(0, 1), (0, 0), (1, 1), (1, 1), (0, 3), (0, 3), (0, 5), (1, 2), (2, 4), (2 , 7), (3, 6), (3, 5), (5, 6), (6, 7)]
SG = SimpleGraph(nodes, edges)

SG.adjacency_matrix

array([[0., 1., 0., 1., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0.]])

In [6]:
SG.incidence_matrix

array([[1., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 1.],
       [0., 0., 0., 0., 0., 1., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0., 0.]])

In [7]:
SG.degree_matrix

array([[3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2.]])

In [8]:
SG.laplacian_matrix

array([[-3.,  1.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -3.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0., -3.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  1.,  0., -1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0., -3.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1., -3.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  1., -2.]])

### Directed Graphs

In [9]:
nodes = [0, 1, 2, 3, 4, 5, 6, 7]
edges = [(0, 1), (0, 3), (0, 5), (1, 2), (2, 1), (1, 4), (1, 7), (2, 3), (2, 4), (3, 5), (5, 6), (6, 7)]
DG = DirectedGraph(nodes, edges)

DG.adjacency_matrix

array([[0., 1., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
DG.incidence_matrix

array([[-1., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0., -1., -1., -1.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0., -1., -1., -1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [11]:
DG.degree_matrix

{'in': array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 2., 0., 0., 0., 0.],
        [0., 0., 0., 0., 2., 0., 0., 0.],
        [0., 0., 0., 0., 0., 2., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 2.]]),
 'out': array([[3., 0., 0., 0., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0., 0., 0., 0.],
        [0., 0., 3., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])}

In [12]:
nodes = [0, 1, 2, 3, 4, 5, 6, 7]
edges = [(0, 1), (0, 3), (0, 5), (1, 2), (2, 1), (1, 4), (1, 7), (2, 3), (2, 4), (3, 5), (5, 6), (6, 7)]
SDG = SimpleDirectedGraph(nodes, edges)

SDG.adjacency_matrix

array([[0., 1., 0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
SDG.incidence_matrix

array([[-1.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0., -1.,  0.],
       [ 1.,  0., -1.,  1.,  0., -1.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0., -1.,  1., -1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.]])

In [14]:
SDG.degree_matrix

{'in': array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 2., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 2., 0., 0., 0., 0.],
        [0., 0., 0., 0., 2., 0., 0., 0.],
        [0., 0., 0., 0., 0., 2., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 2.]]),
 'out': array([[3., 0., 0., 0., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0., 0., 0., 0.],
        [0., 0., 3., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])}

In [15]:
SDG.laplacian_matrix

{'in': array([[ 0., -1.,  0., -1.,  0., -1.,  0.,  0.],
        [ 0.,  2., -1.,  0., -1.,  0.,  0., -1.],
        [ 0., -1.,  1., -1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2.,  0., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  2., -1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.]]),
 'out': array([[ 3., -1.,  0., -1.,  0., -1.,  0.,  0.],
        [ 0.,  3., -1.,  0., -1.,  0.,  0., -1.],
        [ 0., -1.,  3., -1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0., -1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1., -1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])}

### Weighted Graphs

In [16]:
nodes = [0, 1, 2, 3, 4, 5, 6, 7]
edges = [((0, 1), 20), ((0, 3), 30), ((0, 3), 39), ((0, 5), 34), ((1, 2), 34), ((2, 4), 6), ((2 , 7), 76), ((3, 6), 456), ((3, 5), 77), ((5, 6), 66), ((6, 7), 456)]
WG = WeightedGraph(nodes, edges)

WG.adjacency_matrix

array([[  0.,  20.,   0.,  39.,   0.,  34.,   0.,   0.],
       [ 20.,   0.,  34.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  34.,   0.,   0.,   6.,   0.,   0.,  76.],
       [ 39.,   0.,   0.,   0.,   0.,  77., 456.,   0.],
       [  0.,   0.,   6.,   0.,   0.,   0.,   0.,   0.],
       [ 34.,   0.,   0.,  77.,   0.,   0.,  66.,   0.],
       [  0.,   0.,   0., 456.,   0.,  66.,   0., 456.],
       [  0.,   0.,  76.,   0.,   0.,   0., 456.,   0.]])

In [17]:
WG.incidence_matrix

array([[ 20.,  30.,  39.,  34.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 20.,   0.,   0.,   0.,  34.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  34.,   6.,  76.,   0.,   0.,   0.,   0.],
       [  0.,  30.,  39.,   0.,   0.,   0.,   0.,  77., 456.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   6.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  34.,   0.,   0.,   0.,  77.,   0.,  66.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 456.,  66., 456.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  76.,   0.,   0.,   0., 456.]])

In [34]:
WG.degree_matrix

array([[3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2.]])

In [4]:
nodes = [0, 1, 2, 3, 4, 5, 6, 7]
edges = [((0, 1), 20), ((0, 3), 39), ((0, 5), 34), ((1, 2), 34), ((2, 4), 6), ((2 , 7), 76), ((3, 6), 456), ((3, 5), 77), ((5, 6), 66), ((6, 7), 456)]
SWG = SimpleWeightedGraph(nodes, edges)

SWG.adjacency_matrix

array([[  0.,  20.,   0.,  39.,   0.,  34.,   0.,   0.],
       [ 20.,   0.,  34.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  34.,   0.,   0.,   6.,   0.,   0.,  76.],
       [ 39.,   0.,   0.,   0.,   0.,  77., 456.,   0.],
       [  0.,   0.,   6.,   0.,   0.,   0.,   0.,   0.],
       [ 34.,   0.,   0.,  77.,   0.,   0.,  66.,   0.],
       [  0.,   0.,   0., 456.,   0.,  66.,   0., 456.],
       [  0.,   0.,  76.,   0.,   0.,   0., 456.,   0.]])

In [5]:
SWG.incidence_matrix

array([[ 20.,  39.,  34.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 20.,   0.,   0.,  34.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  34.,   6.,  76.,   0.,   0.,   0.,   0.],
       [  0.,  39.,   0.,   0.,   0.,   0.,  77., 456.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   6.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  34.,   0.,   0.,   0.,  77.,   0.,  66.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., 456.,  66., 456.],
       [  0.,   0.,   0.,   0.,   0.,  76.,   0.,   0.,   0., 456.]])

In [6]:
SWG.degree_matrix

array([[3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2.]])

In [7]:
SWG.laplacian_matrix

array([[-3.,  1.,  0.,  1.,  0.,  1.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -3.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0., -3.,  0.,  1.,  1.,  0.],
       [ 0.,  0.,  1.,  0., -1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.,  0., -3.,  1.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1., -3.,  1.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  1., -2.]])

In [20]:
if len(SWG.edges) == SWG.incidence_matrix.shape[1]:
    print('dimension are okay')
else: print('Error')
if WG.incidence_matrix.shape[1] == SWG.incidence_matrix.shape[1]:
    print('Given the test data the dimesnions should be different')
else: print('seems fine')

dimension are okay
seems fine


## Graph Generator

In [28]:
factory = RandomGraphFactory()
graph1 = factory.generate_graph(8, 7)
graph1.adjacency_matrix

[(5, 6), (2, 5), (5, 6), (4, 1), (6, 0), (1, 0), (6, 3)]


array([[0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 0.]])

In [29]:
graph2 = factory.generate_graph(10, 10, directed=True)
graph2.adjacency_matrix

[(5, 8), (7, 0), (1, 7), (7, 5), (2, 5), (2, 7), (1, 1), (8, 1), (8, 3), (3, 3)]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0.]])

In [30]:
graph3 = factory.generate_graph(10, 10, weighted=True)
graph3.adjacency_matrix

[((4, 0), 32), ((4, 4), 9), ((4, 1), 51), ((1, 5), 21), ((1, 8), 40), ((3, 5), 96), ((5, 3), 81), ((5, 8), 21), ((3, 6), 13), ((7, 4), 95)]


array([[ 0.,  0.,  0.,  0., 32.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 51., 21.,  0.,  0., 40.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 81., 13.,  0.,  0.],
       [32., 51.,  0.,  0.,  0.,  0.,  0., 95.,  0.],
       [ 0., 21.,  0., 81.,  0.,  0.,  0.,  0., 21.],
       [ 0.,  0.,  0., 13.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 95.,  0.,  0.,  0.,  0.],
       [ 0., 40.,  0.,  0.,  0., 21.,  0.,  0.,  0.]])

In [31]:
graph4 = factory.generate_graph(10, simple=False)
graph4.adjacency_matrix

[(3, 5)]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
graph5 = factory.generate_graph(10, simple=False, directed=True)
graph5.adjacency_matrix

[(3, 7), (3, 7), (8, 7), (2, 0), (1, 4), (7, 5), (5, 5), (6, 5), (2, 0), (8, 0), (0, 1), (0, 6), (6, 3), (8, 1), (8, 1), (0, 6), (1, 8), (0, 6), (4, 8), (1, 5), (1, 1), (7, 3), (2, 1), (4, 6)]


array([[0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 1., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 1., 0.]])

In [33]:
graph6 = factory.generate_graph(10, simple=False, weighted=True)
graph6.adjacency_matrix

[((2, 0), 38), ((6, 1), 44), ((3, 7), 97), ((2, 4), 70), ((0, 7), 31), ((0, 5), 40), ((2, 4), 30), ((3, 7), 59), ((5, 6), 58), ((7, 7), 26), ((0, 6), 17), ((5, 1), 77), ((0, 2), 67), ((7, 1), 29), ((2, 6), 72), ((2, 1), 14), ((8, 4), 57), ((6, 5), 67), ((7, 1), 0), ((5, 1), 84), ((1, 5), 22), ((8, 6), 62), ((4, 6), 76), ((2, 4), 57), ((8, 5), 3), ((8, 4), 49), ((5, 2), 73), ((5, 8), 26), ((2, 1), 89), ((7, 0), 38), ((6, 3), 86), ((7, 7), 5), ((3, 5), 65), ((8, 8), 96), ((3, 7), 79), ((0, 3), 40), ((4, 0), 61)]


array([[ 0.,  0., 38., 40., 61., 40., 17., 38.,  0.],
       [ 0.,  0., 89.,  0.,  0., 84., 44.,  0.,  0.],
       [38., 89.,  0.,  0., 57., 73., 72.,  0.,  0.],
       [40.,  0.,  0.,  0.,  0., 65., 86., 79.,  0.],
       [61.,  0., 57.,  0.,  0.,  0., 76.,  0., 49.],
       [40., 84., 73., 65.,  0.,  0., 67.,  0.,  3.],
       [17., 44., 72., 86., 76., 67.,  0.,  0., 62.],
       [38.,  0.,  0., 79.,  0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0., 49.,  3., 62.,  0., 96.]])

# Data Transformer

In [23]:
nodes = [0, 1, 2, 3, 4, 5, 6, 7]
edges = [(0, 1), (0, 3), (0, 5), (1, 2), (2, 1), (1, 4), (1, 7), (2, 3), (2, 4), (3, 5), (5, 6), (6, 7)]

dt = DataTransformer()
dt.transform_input(nodes, edges, weighted=False)

([0, 1, 2, 3, 4, 5, 6, 7],
 [(0, 1),
  (0, 3),
  (0, 5),
  (1, 2),
  (2, 1),
  (1, 4),
  (1, 7),
  (2, 3),
  (2, 4),
  (3, 5),
  (5, 6),
  (6, 7)])

In [22]:
nodes = ['e', '5', '7', '4']
edges = [('e', '7'), ('e', '7'), ( '7', '5'), ('e','5'), ('5','4')]

dt = DataTransformer()
dt.transform_input(nodes, edges, weighted=False)

([0, 1, 2, 3], [(0, 2), (0, 2), (2, 1), (0, 1), (1, 3)])

In [24]:
ob = object()

nodes = ['e', '5', '7', '4', ob]
edges = [('e', '7'), ('e', ob), ( '7', '5'), ('e','5'), ('5','4')]

dt = DataTransformer()
dt.transform_input(nodes, edges, weighted=False)

([0, 1, 2, 3, 4], [(0, 2), (0, 4), (2, 1), (0, 1), (1, 3)])

In [27]:
nodes = [0, 1, 2, 3, 4, 5, 6, '8', ob]
edges = [((0, 1), 20), ((0, 3), 39), ((0, 5), 34), ((1, '8'), 34), ((2, 4), 6), ((2 , ob), 76), ((ob, 6), 456), ((3, 5), 77), ((5, 6), 66), ((6, '8'), 456)]
dt = DataTransformer()
dt.transform_input(nodes, edges, weighted=True)

([0, 1, 2, 3, 4, 5, 6, 7, 8],
 [(0, 1),
  (0, 3),
  (0, 5),
  (1, 7),
  (2, 4),
  (2, 8),
  (8, 6),
  (3, 5),
  (5, 6),
  (6, 7)])

# Garbage garage